### ISSUE TITLE
possible to get a signed (unlisted) version?

### ISSUE THREAD

**Issue by Andy2244** [wagle/resize-bookmarks-editor#1]
Hi,

it seems it just took 8 years until we might get a fix for the tiny edit bookmark window, so thx in advance for trying to fix this bug in the main repo.

As for this extension, is it possible to get a signed version, so i can install it manually in a "stable" FF version?

thx
Andy

**Comment by Andy2244** [comment]
Found the signing [documentation](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) and signing worked for the generated xpi.

**Comment by wagle** [comment]
Sorry for the delay, been preoccupied.  What's the patch? 

Note that this version is a work-in-progress.

**Comment by Andy2244** [comment]
No patch, just could not test/install this version with a stable branch firefox 50. That's because you can't disable the signing via about:config anymore. So either i had to use the dev/nightly builds or manually sign the xpi as documented in the link above.

This version seems also not mutiprocess compatible, so would be nice to convert it to a webextension.

thx
Andy

**Comment by wagle** [comment]
Ah, sorry, I use ESR 45 because it still has a cancel function on bookmark editing.  I wasn't guaranteeing that this intermediate version works.  Does it?

The goal is to figure out the minimum necessary to get it to work, and transfer that webextensions or the actual editor itself.

Now that someone has indicated interest in this Quixotic quest, I feel much more motivated.  I was largely investigating Tofino as the thing to explore.

**Comment by Andy2244** [comment]
Yeah, i was using Edit Bookmark Plus for some years, but since Firefox now uses multiprocess by default i tried to cleanup all my incompatible addons. The only one i could not find a replacement/update for was for EBP. Its still baffling to my how anyone could use this tiny add/edit bookmark window, which only shows 5 folders of your bookmarks even if expanded. So i'm gratefully someone is trying to fix this long standing problem.

From my test in FF50, the resize only works to a certain size, while the drag directions are also inverted. So i also could not resize it to what EBP allowed me too. It also did not seem to store the last state, so if i expanded the view the last time, i would expect it to stay this way for the next add/edit.

**Comment by wagle** [comment]
Its tuned to my particular use case: editing tags.  Are you editing folders or tags?

**Comment by wagle** [comment]
.. that is, gotta do some work to get it to resize both list-boxes.

**Comment by Andy2244** [comment]
I'm not editing at all :)

I mainly use it to add new bookmarks, that i want to directly store in the correct sub-folder, instead of just a recently used or "unsorted". I have like 100 different bookmark folders (categories) and its a pain to add a new bookmark in a folder that i did not recently used. Even so the recently used list has only 5 entries as well.

If i need to move the bookmarks or edit them i use the ctrl+shift+b editor.

**Comment by wagle** [comment]
Ok, my webstorm subscription lapsed, and I have no money for a bit, working on solving that.

**Comment by wagle** [comment]
Oh wait, he fixes some folder problem that I don't understand, so was removing it.  Do you know if you use that patch?   What exactly does it do?

**Comment by wagle** [comment]
And oh yeah, try tweaking the prefs to see if you can get the resizing to work right for you.

**Comment by Andy2244** [comment]
Let me just open a clear issue for the problems i found, so we keep this organized :p
